/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 20:00:06 GMT 2025
 */

package MakeItFit.menu;

import MakeItFit.menu.MenuItem;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS                = true,
                     useVNET               = true,
                     resetStaticState      = true,
                     useJEE                = true)
public class MenuItem_ESTest extends MenuItem_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem((String) null, menuItem_Handler0);
        boolean  boolean0  = menuItem0.isValid();
        assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        MenuItem.PreCondition menuItem_PreCondition0 =
            mock(MenuItem.PreCondition.class, new ViolatedAssumptionAnswer());
        doReturn(false).when(menuItem_PreCondition0).validate();
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem("", menuItem_PreCondition0, menuItem_Handler0);
        boolean  boolean0  = menuItem0.isValid();
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem("^MBBb1-[", menuItem_Handler0);
        String   string0   = menuItem0.getName();
        assertEquals("^MBBb1-[", string0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem("", menuItem_Handler0);
        String   string0   = menuItem0.getName();
        assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test4() throws Throwable {
        MenuItem menuItem0 = new MenuItem("r|}0+X", (MenuItem.Handler) null);
        // Undeclared exception!
        try {
            menuItem0.execute();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("MakeItFit.menu.MenuItem", e);
        }
    }

    @Test(timeout = 4000)
    public void test5() throws Throwable {
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem((String) null, menuItem_Handler0);
        menuItem0.execute();
        assertNull(menuItem0.getName());
    }

    @Test(timeout = 4000)
    public void test6() throws Throwable {
        MenuItem.PreCondition menuItem_PreCondition0 =
            mock(MenuItem.PreCondition.class, new ViolatedAssumptionAnswer());
        doReturn(false).when(menuItem_PreCondition0).validate();
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem("", menuItem_PreCondition0, menuItem_Handler0);
        menuItem0.execute();
        assertEquals("", menuItem0.getName());
    }

    @Test(timeout = 4000)
    public void test7() throws Throwable {
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem((String) null, menuItem_Handler0);
        String   string0   = menuItem0.getName();
        assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test8() throws Throwable {
        MenuItem.Handler menuItem_Handler0 =
            mock(MenuItem.Handler.class, new ViolatedAssumptionAnswer());
        MenuItem menuItem0 = new MenuItem("", (MenuItem.PreCondition) null, menuItem_Handler0);
        // Undeclared exception!
        try {
            menuItem0.isValid();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("MakeItFit.menu.MenuItem", e);
        }
    }
}
