/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 19:55:48 GMT 2025
 */

package MakeItFit.utils;

import MakeItFit.utils.EmailValidator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS                = true,
                     useVNET               = true,
                     resetStaticState      = true,
                     useJEE                = true)
public class EmailValidator_ESTest extends EmailValidator_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        boolean boolean0 = EmailValidator.isValidEmail("?:!@?:?:0.0");
        //  // Unstable assertion: assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        // Undeclared exception!
        try {
            EmailValidator.isValidEmail((String) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("java.util.regex.Matcher", e);
        }
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        boolean boolean0 = EmailValidator.isValidEmail("");
        assertFalse(boolean0);
    }

    @Test(timeout = 4000)
    public void test3() throws Throwable {
        EmailValidator emailValidator0 = new EmailValidator();
    }
}
