/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 19:55:29 GMT 2025
 */

package MakeItFit.exceptions;

import MakeItFit.exceptions.EntityDoesNotExistException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS                = true,
                     useVNET               = true,
                     resetStaticState      = true,
                     useJEE                = true)
public class EntityDoesNotExistException_ESTest
    extends EntityDoesNotExistException_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        EntityDoesNotExistException entityDoesNotExistException0 =
            new EntityDoesNotExistException();
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        EntityDoesNotExistException entityDoesNotExistException0 =
            new EntityDoesNotExistException("j\"");
    }
}
