/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 20:32:17 GMT 2025
 */

package MakeItFit.views;

import java.util.NoSuchElementException;

import MakeItFit.menu.Menu;
import MakeItFit.views.AdminView;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS                = true,
                     useVNET               = true,
                     resetStaticState      = true,
                     useJEE                = true)
public class AdminView_ESTest extends AdminView_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        AdminView adminView0 = new AdminView();
        SystemInUtil.addInputLine("Q=p]h`: ^7!>");
        adminView0.removeUser();
    }

    @Test(timeout = 4000)
    public void test01() throws Throwable {
        SystemInUtil.addInputLine("J)O44");
        AdminView adminView0 = new AdminView();
        adminView0.executeQueryHowManyKMsDone();
    }

    @Test(timeout = 4000)
    public void test02() throws Throwable {
        SystemInUtil.addInputLine("sv(-DCZu");
        AdminView adminView0 = new AdminView();
        adminView0.executeQueryHowManyAltimetryDone();
    }

    @Test(timeout = 4000)
    public void test03() throws Throwable {
        SystemInUtil.addInputLine(
            "Which user has carried out the most activities in a period or ever since?");
        AdminView adminView0 = new AdminView();
        adminView0.executeQueryGetAllActivitiesFromUser();
    }

    @Test(timeout = 4000)
    public void test04() throws Throwable {
        SystemInUtil.addInputLine("8");
        AdminView adminView0 = new AdminView();
        adminView0.executeQueries();
    }

    @Test(timeout = 4000)
    public void test05() throws Throwable {
        AdminView adminView0 = new AdminView();
        Menu      menu0      = adminView0.createQueryMenu();
        assertNotNull(menu0);
    }

    @Test(timeout = 4000)
    public void test06() throws Throwable {
        SystemInUtil.addInputLine("y");
        AdminView adminView0 = new AdminView();
        adminView0.executeQueryWhoDidTheMostActivities();
    }

    @Test(timeout = 4000)
    public void test07() throws Throwable {
        SystemInUtil.addInputLine("8");
        AdminView adminView0 = new AdminView();
        adminView0.executeQueryWhoDidTheMostActivities();
    }

    @Test(timeout = 4000)
    public void test08() throws Throwable {
        AdminView adminView0 = new AdminView();
        SystemInUtil.addInputLine("Y");
        adminView0.executeQueryWhoDidTheMostActivities();
    }

    @Test(timeout = 4000)
    public void test09() throws Throwable {
        AdminView adminView0 = new AdminView();
        SystemInUtil.addInputLine("s");
        adminView0.executeQuerywhoBurnsMoreCalories();
    }

    @Test(timeout = 4000)
    public void test10() throws Throwable {
        SystemInUtil.addInputLine("y");
        AdminView adminView0 = new AdminView();
        adminView0.executeQuerywhoBurnsMoreCalories();
    }

    @Test(timeout = 4000)
    public void test11() throws Throwable {
        SystemInUtil.addInputLine("Y");
        AdminView adminView0 = new AdminView();
        adminView0.executeQuerywhoBurnsMoreCalories();
    }

    @Test(timeout = 4000)
    public void test12() throws Throwable {
        SystemInUtil.addInputLine("x");
        AdminView adminView0 = new AdminView();
        // Undeclared exception!
        try {
            adminView0.login();
            fail("Expecting exception: NoSuchElementException");

        } catch (NoSuchElementException e) {
            //
            // No line found
            //
            verifyException("java.util.Scanner", e);
        }
    }

    @Test(timeout = 4000)
    public void test13() throws Throwable {
        SystemInUtil.addInputLine("Y");
        AdminView adminView0 = new AdminView();
        // Undeclared exception!
        try {
            adminView0.login();
            fail("Expecting exception: NoSuchElementException");

        } catch (NoSuchElementException e) {
            //
            // No line found
            //
            verifyException("java.util.Scanner", e);
        }
    }

    @Test(timeout = 4000)
    public void test14() throws Throwable {
        SystemInUtil.addInputLine("y");
        AdminView adminView0 = new AdminView();
        try {
            adminView0.setNewEmail();
            fail("Expecting exception: RuntimeException");

        } catch (RuntimeException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("MakeItFit.views.AdminView", e);
        }
    }

    @Test(timeout = 4000)
    public void test15() throws Throwable {
        SystemInUtil.addInputLine("y");
        AdminView adminView0 = new AdminView();
        try {
            adminView0.setEmail();
            fail("Expecting exception: RuntimeException");

        } catch (RuntimeException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("MakeItFit.views.AdminView", e);
        }
    }

    @Test(timeout = 4000)
    public void test16() throws Throwable {
        SystemInUtil.addInputLine("y");
        SystemInUtil.addInputLine("y");
        AdminView adminView0 = new AdminView();
        // Undeclared exception!
        try {
            adminView0.login();
            fail("Expecting exception: NoSuchElementException");

        } catch (NoSuchElementException e) {
            //
            // No line found
            //
            verifyException("java.util.Scanner", e);
        }
    }

    @Test(timeout = 4000)
    public void test17() throws Throwable {
        AdminView adminView0 = new AdminView();
        adminView0.executeQueryMostDoneActivity();
    }

    @Test(timeout = 4000)
    public void test18() throws Throwable {
        AdminView adminView0 = new AdminView();
        adminView0.executeQueryMostDemandingTrainingPlan();
    }

    @Test(timeout = 4000)
    public void test19() throws Throwable {
        AdminView adminView0 = new AdminView();
        adminView0.listAllTrainingPlans();
    }

    @Test(timeout = 4000)
    public void test20() throws Throwable {
        AdminView adminView0 = new AdminView();
        adminView0.executeQueries();
    }

    @Test(timeout = 4000)
    public void test21() throws Throwable {
        AdminView adminView0 = new AdminView();
        // Undeclared exception!
        try {
            adminView0.removeUser();
            fail("Expecting exception: NoSuchElementException");

        } catch (NoSuchElementException e) {
            //
            // No line found
            //
            verifyException("java.util.Scanner", e);
        }
    }

    @Test(timeout = 4000)
    public void test22() throws Throwable {
        AdminView adminView0 = new AdminView();
        adminView0.printAllUsersDetails();
    }
}
