/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 20:09:51 GMT 2025
 */

package MakeItFit.activities;

import MakeItFit.activities.ActivityManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS                = true,
                     useVNET               = true,
                     resetStaticState      = true,
                     useJEE                = true)
public class ActivityManager_ESTest extends ActivityManager_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        ActivityManager activityManager0 = new ActivityManager();
        activityManager0.random          = null;
        // Undeclared exception!
        try {
            activityManager0.getRandomActivity();
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("MakeItFit.activities.ActivityManager", e);
        }
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        ActivityManager activityManager0 = new ActivityManager();
        String          string0          = activityManager0.getRandomActivity();
        assertEquals("PushUp", string0);
    }
}
