/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 04 20:34:16 GMT 2025
 */

package MakeItFit;

import java.util.NoSuchElementException;

import MakeItFit.Main;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.Test;
import org.junit.runner.RunWith;

import static org.evosuite.runtime.EvoAssertions.*;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS                = true,
                     useVNET               = true,
                     resetStaticState      = true,
                     useJEE                = true)
public class Main_ESTest extends Main_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
        SystemInUtil.addInputLine("4");
        String[] stringArray0 = new String[1];
        Main.main(stringArray0);
        assertEquals(1, stringArray0.length);
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Main main0 = new Main();
    }

    @Test(timeout = 4000)
    public void test2() throws Throwable {
        String[] stringArray0 = new String[1];
        // Undeclared exception!
        try {
            Main.main(stringArray0);
            fail("Expecting exception: NoSuchElementException");

        } catch (NoSuchElementException e) {
            //
            // No line found
            //
            verifyException("java.util.Scanner", e);
        }
    }
}
