/**
 * Scaffolding file used to store all the setups needed to run
 * tests automatically generated by EvoSuite
 * Wed Jun 04 20:33:25 GMT 2025
 */

package MakeItFit;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;

@EvoSuiteClassExclude
public class MakeItFit_ESTest_scaffolding {

    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr =
        new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

    private static final java.util.Properties defaultProperties =
        (java.util.Properties) java.lang.System.getProperties().clone();

    private org.evosuite.runtime.thread.ThreadStopper threadStopper =
        new org.evosuite.runtime.thread.ThreadStopper(
            org.evosuite.runtime.thread.KillSwitchHandler.getInstance(),
            3000);

    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "MakeItFit.MakeItFit";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads           = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn                 = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode =
            org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    public static void setSystemProperties() {

        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("file.encoding", "UTF-8");
        java.lang.System.setProperty("java.awt.headless", "true");
        java.lang.System.setProperty("java.io.tmpdir", "/tmp");
        java.lang.System.setProperty("user.country", "US");
        java.lang.System.setProperty("user.dir", "/home/voidbert/ATS");
        java.lang.System.setProperty("user.home", "/home/voidbert");
        java.lang.System.setProperty("user.language", "en");
        java.lang.System.setProperty("user.name", "voidbert");
        java.lang.System.setProperty("user.timezone", "Europe/Lisbon");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(
            MakeItFit_ESTest_scaffolding.class.getClassLoader(),
            "MakeItFit.exceptions.InvalidTypeException",
            "MakeItFit.activities.ActivityInterface",
            "MakeItFit.trainingPlan.TrainingPlan",
            "MakeItFit.activities.types.DistanceWithAltimetry",
            "MakeItFit.exceptions.EntityDoesNotExistException",
            "MakeItFit.activities.implementation.PushUp",
            "MakeItFit.users.types.Amateur",
            "MakeItFit.queries.QueriesManager",
            "MakeItFit.activities.types.Repetitions",
            "MakeItFit.queries.MostDemandingTrainingPlan",
            "MakeItFit.users.User",
            "MakeItFit.activities.types.Distance",
            "MakeItFit.activities.HardInterface",
            "MakeItFit.users.types.Professional",
            "MakeItFit.MakeItFit",
            "MakeItFit.users.UserInterface",
            "MakeItFit.utils.MyTuple",
            "MakeItFit.users.Gender",
            "MakeItFit.utils.MakeItFitDate",
            "MakeItFit.trainingPlan.TrainingPlanManager",
            "MakeItFit.exceptions.ExistingEntityConflictException",
            "MakeItFit.queries.WhoDidTheMostActivities",
            "MakeItFit.users.types.Occasional",
            "MakeItFit.activities.Activity",
            "MakeItFit.queries.MostDoneActivity",
            "MakeItFit.activities.types.RepetitionsWithWeights",
            "MakeItFit.activities.implementation.Trail",
            "MakeItFit.queries.WhoBurnsMoreCalories",
            "MakeItFit.queries.HowManyKMsDone",
            "MakeItFit.users.UserManager",
            "MakeItFit.activities.implementation.Running",
            "MakeItFit.queries.HowManyAltimetryDone",
            "MakeItFit.activities.implementation.WeightSquat");
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(
            MakeItFit_ESTest_scaffolding.class.getClassLoader());

        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
            "MakeItFit.MakeItFit",
            "MakeItFit.users.UserManager",
            "MakeItFit.trainingPlan.TrainingPlanManager",
            "MakeItFit.queries.QueriesManager",
            "MakeItFit.queries.HowManyAltimetryDone",
            "MakeItFit.queries.HowManyKMsDone",
            "MakeItFit.queries.MostDoneActivity",
            "MakeItFit.queries.MostDemandingTrainingPlan",
            "MakeItFit.queries.WhoBurnsMoreCalories",
            "MakeItFit.queries.WhoDidTheMostActivities",
            "MakeItFit.utils.MakeItFitDate",
            "MakeItFit.trainingPlan.TrainingPlan",
            "MakeItFit.exceptions.EntityDoesNotExistException",
            "MakeItFit.users.User",
            "MakeItFit.users.types.Amateur",
            "MakeItFit.exceptions.InvalidTypeException",
            "MakeItFit.users.types.Occasional",
            "MakeItFit.activities.Activity",
            "MakeItFit.activities.types.Distance",
            "MakeItFit.activities.implementation.Running",
            "MakeItFit.activities.types.Repetitions",
            "MakeItFit.activities.implementation.PushUp",
            "MakeItFit.activities.types.RepetitionsWithWeights",
            "MakeItFit.activities.implementation.WeightSquat",
            "MakeItFit.activities.types.DistanceWithAltimetry",
            "MakeItFit.activities.implementation.Trail",
            "MakeItFit.users.types.Professional",
            "MakeItFit.utils.MyTuple");
    }
}
