name: Maintenance checks
on:
    pull_request:
        paths:
            - '.github/workflows/**'
            - 'src/**'
            - 'build.gradle.kts'
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
            - run: >-
                   sudo apt update                                                   &&
                   sudo apt install wget                                             &&
                   wget https://apt.llvm.org/llvm.sh                                 &&
                   sudo bash ./llvm.sh 19                                            &&
                   (sudo rm /usr/bin/clang-format || exit 0)                         &&
                   sudo apt -y install clang-format-19
            - run: gradle format

    build:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - run: ./gradlew --no-daemon build
